/*
  This file is automatically generated. Any changes will be overwritten.
  Modify app.module.ts instead.
*/
import { APP_INITIALIZER } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { BrowserAnimationsModule } from '@angular/platform-browser/animations';
import { FormsModule } from '@angular/forms';
import { HttpClientModule, HTTP_INTERCEPTORS } from '@angular/common/http';
import { BodyModule } from '@radzen/angular/dist/body';
import { CardModule } from '@radzen/angular/dist/card';
import { ContentContainerModule } from '@radzen/angular/dist/content-container';
import { HeaderModule } from '@radzen/angular/dist/header';
import { SidebarToggleModule } from '@radzen/angular/dist/sidebar-toggle';
import { LabelModule } from '@radzen/angular/dist/label';
import { SidebarModule } from '@radzen/angular/dist/sidebar';
import { PanelMenuModule } from '@radzen/angular/dist/panelmenu';
import { FooterModule } from '@radzen/angular/dist/footer';
import { ContentModule } from '@radzen/angular/dist/content';
import { HeadingModule } from '@radzen/angular/dist/heading';
import { GridModule } from '@radzen/angular/dist/grid';
import { FormModule } from '@radzen/angular/dist/form';
import { DropDownModule } from '@radzen/angular/dist/dropdown';
import { SSRSViewerModule } from '@radzen/angular/dist/ssrsviewer';
import { SharedModule } from '@radzen/angular/dist/shared';
import { NotificationModule } from '@radzen/angular/dist/notification';
import { DialogModule } from '@radzen/angular/dist/dialog';

import { ConfigService, configServiceFactory } from './config.service';
import { AppRoutes } from './app.routes';
import { AppComponent } from './app.component';
import { CacheInterceptor } from './cache.interceptor';
export { AppComponent } from './app.component';
import { PapeisComponent } from './papeis/papeis.component';
import { AddPapeiComponent } from './add-papei/add-papei.component';
import { EditPapeiComponent } from './edit-papei/edit-papei.component';
import { PessoasComponent } from './pessoas/pessoas.component';
import { AddPessoaComponent } from './add-pessoa/add-pessoa.component';
import { EditPessoaComponent } from './edit-pessoa/edit-pessoa.component';
import { ProjetosComponent } from './projetos/projetos.component';
import { AddProjetoComponent } from './add-projeto/add-projeto.component';
import { EditProjetoComponent } from './edit-projeto/edit-projeto.component';
import { TarefasComponent } from './tarefas/tarefas.component';
import { AddTarefaComponent } from './add-tarefa/add-tarefa.component';
import { EditTarefaComponent } from './edit-tarefa/edit-tarefa.component';
import { TarefasPorProjetoComponent } from './tarefas-por-projeto/tarefas-por-projeto.component';
import { RelatorioComponent } from './relatório/relatório.component';
import { LoginLayoutComponent } from './login-layout/login-layout.component';
import { MainLayoutComponent } from './main-layout/main-layout.component';

import { CprojdsService } from './cprojds.service';

export const PageDeclarations = [
  PapeisComponent,
  AddPapeiComponent,
  EditPapeiComponent,
  PessoasComponent,
  AddPessoaComponent,
  EditPessoaComponent,
  ProjetosComponent,
  AddProjetoComponent,
  EditProjetoComponent,
  TarefasComponent,
  AddTarefaComponent,
  EditTarefaComponent,
  TarefasPorProjetoComponent,
  RelatorioComponent,
];

export const LayoutDeclarations = [
  LoginLayoutComponent,
  MainLayoutComponent,
];

export const AppDeclarations = [
  ...PageDeclarations,
  ...LayoutDeclarations,
  AppComponent
];

export const AppProviders = [
  {
    provide: HTTP_INTERCEPTORS,
    useClass: CacheInterceptor,
    multi: true
  },
  CprojdsService,
  ConfigService,
  {
    provide: APP_INITIALIZER,
    useFactory: configServiceFactory,
    deps: [ConfigService],
    multi: true
  }
];

export const AppImports = [
  BrowserModule,
  BrowserAnimationsModule,
  FormsModule,
  HttpClientModule,
  BodyModule,
  CardModule,
  ContentContainerModule,
  HeaderModule,
  SidebarToggleModule,
  LabelModule,
  SidebarModule,
  PanelMenuModule,
  FooterModule,
  ContentModule,
  HeadingModule,
  GridModule,
  FormModule,
  DropDownModule,
  SSRSViewerModule,
  SharedModule,
  NotificationModule,
  DialogModule,
  AppRoutes
];
