/*
  This file is automatically generated. Any changes will be overwritten.
  Modify tarefas.component.ts instead.
*/
import { ChangeDetectorRef, ViewChild, AfterViewInit, Injector, OnInit, OnDestroy } from '@angular/core';
import { Router, ActivatedRoute } from '@angular/router';
import { Location } from '@angular/common';
import { Subscription } from 'rxjs';

import { DialogService, DIALOG_PARAMETERS, DialogRef } from '@radzen/angular/dist/dialog';
import { NotificationService } from '@radzen/angular/dist/notification';
import { ContentComponent } from '@radzen/angular/dist/content';
import { HeadingComponent } from '@radzen/angular/dist/heading';
import { GridComponent } from '@radzen/angular/dist/grid';
import { AddTarefaComponent } from '../add-tarefa/add-tarefa.component';
import { EditTarefaComponent } from '../edit-tarefa/edit-tarefa.component';

import { CprojdsService } from '../cprojds.service';

export class TarefasGenerated implements AfterViewInit, OnInit, OnDestroy {
  // Components
  @ViewChild('content1') content1: ContentComponent;
  @ViewChild('pageTitle') pageTitle: HeadingComponent;
  @ViewChild('grid0') grid0: GridComponent;

  router: Router;

  cd: ChangeDetectorRef;

  route: ActivatedRoute;

  notificationService: NotificationService;

  dialogService: DialogService;

  dialogRef: DialogRef;

  _location: Location;

  _subscription: Subscription;

  cprojds: CprojdsService;

  orderBy: any;

  getTarefasResult: any;

  getTarefasCount: any;

  parameters: any;

  constructor(private injector: Injector) {
  }

  ngOnInit() {
    this.notificationService = this.injector.get(NotificationService);

    this.dialogService = this.injector.get(DialogService);

    this.dialogRef = this.injector.get(DialogRef, null);

    this.router = this.injector.get(Router);

    this.cd = this.injector.get(ChangeDetectorRef);

    this._location = this.injector.get(Location);

    this.route = this.injector.get(ActivatedRoute);

    this.cprojds = this.injector.get(CprojdsService);
  }

  ngAfterViewInit() {
    this._subscription = this.route.params.subscribe(parameters => {
      if (this.dialogRef) {
        this.parameters = this.injector.get(DIALOG_PARAMETERS);
      } else {
        this.parameters = parameters;
      }
      this.load();
      this.cd.detectChanges();
    });
  }

  ngOnDestroy() {
    this._subscription.unsubscribe();
  }


  load() {
    this.orderBy = 'tarefa1 desc';

    this.cprojds.getTarefas(null, this.grid0.allowPaging ? this.grid0.pageSize : null, this.grid0.allowPaging ? 0 : null, `${this.orderBy}`, this.grid0.allowPaging, `Pessoa,Projeto1`, null, null)
    .subscribe((result: any) => {
      this.getTarefasResult = result.value;

      this.getTarefasCount = this.grid0.allowPaging ? result['@odata.count'] : result.value.length;
    }, (result: any) => {

    });
  }

  grid0Add(event: any) {
    this.dialogService.open(AddTarefaComponent, { parameters: {}, title: 'Add Tarefa' });
  }

  grid0Delete(event: any) {
    this.cprojds.deleteTarefa(event.Tarefa1)
    .subscribe((result: any) => {
      this.notificationService.notify({ severity: "success", summary: `Success`, detail: `Tarefa deleted!` });
    }, (result: any) => {
      this.notificationService.notify({ severity: "error", summary: `Error`, detail: `Unable to delete Tarefa` });
    });
  }

  grid0LoadData(event: any) {
    let usedOrder: string = event.orderby;

    if (event.orderby == '') {
      usedOrder = this.orderBy;
    }

    this.cprojds.getTarefas(`${event.filter}`, event.top, event.skip, `${usedOrder}`, event.top != null && event.skip != null, `Pessoa,Projeto1`, null, null)
    .subscribe((result: any) => {
      this.getTarefasResult = result.value;

      this.getTarefasCount = event.top != null && event.skip != null ? result['@odata.count'] : result.value.length;

      
    }, (result: any) => {

    });
  }

  grid0RowSelect(event: any) {
    this.dialogService.open(EditTarefaComponent, { parameters: {Tarefa1: event.Tarefa1}, title: 'Edit Tarefa' });
  }
}
