/*
  This file is automatically generated. Any changes will be overwritten.
  Modify edit-projeto.component.ts instead.
*/
import { ChangeDetectorRef, ViewChild, AfterViewInit, Injector, OnInit, OnDestroy } from '@angular/core';
import { Router, ActivatedRoute } from '@angular/router';
import { Location } from '@angular/common';
import { Subscription } from 'rxjs';

import { DialogService, DIALOG_PARAMETERS, DialogRef } from '@radzen/angular/dist/dialog';
import { NotificationService } from '@radzen/angular/dist/notification';
import { ContentComponent } from '@radzen/angular/dist/content';
import { FormComponent } from '@radzen/angular/dist/form';

import { Cproj3DsService } from '../cproj-3-ds.service';

export class EditProjetoGenerated implements AfterViewInit, OnInit, OnDestroy {
  // Components
  @ViewChild('content1') content1: ContentComponent;
  @ViewChild('form0') form0: FormComponent;

  router: Router;

  cd: ChangeDetectorRef;

  route: ActivatedRoute;

  notificationService: NotificationService;

  dialogService: DialogService;

  dialogRef: DialogRef;

  _location: Location;

  _subscription: Subscription;

  cproj3Ds: Cproj3DsService;

  projeto: any;

  getPessoasResult: any;

  getPessoasCount: any;

  parameters: any;

  constructor(private injector: Injector) {
  }

  ngOnInit() {
    this.notificationService = this.injector.get(NotificationService);

    this.dialogService = this.injector.get(DialogService);

    this.dialogRef = this.injector.get(DialogRef, null);

    this.router = this.injector.get(Router);

    this.cd = this.injector.get(ChangeDetectorRef);

    this._location = this.injector.get(Location);

    this.route = this.injector.get(ActivatedRoute);

    this.cproj3Ds = this.injector.get(Cproj3DsService);
  }

  ngAfterViewInit() {
    this._subscription = this.route.params.subscribe(parameters => {
      if (this.dialogRef) {
        this.parameters = this.injector.get(DIALOG_PARAMETERS);
      } else {
        this.parameters = parameters;
      }
      this.load();
      this.cd.detectChanges();
    });
  }

  ngOnDestroy() {
    this._subscription.unsubscribe();
  }


  load() {
    this.cproj3Ds.getProjetoByProjeto1(this.parameters.Projeto1)
    .subscribe((result: any) => {
      this.projeto = result;
    }, (result: any) => {

    });

    this.cproj3Ds.getPessoas(null, (<any>this.form0.fields.find(f => f.property == 'Cliente')).pageSize, 0, null, true, null, null, null)
    .subscribe((result: any) => {
      this.getPessoasResult = result.value;

      this.getPessoasCount = result['@odata.count'];
    }, (result: any) => {

    });
  }

  form0Cancel(event: any) {
    if (this.dialogRef) {
      this.dialogRef.close();
    } else {
      this._location.back();
    }
  }

  form0Submit(event: any) {
    this.cproj3Ds.updateProjeto(this.parameters.Projeto1, event)
    .subscribe((result: any) => {
      if (this.dialogRef) {
        this.dialogRef.close();
      } else {
        this._location.back();
      }
    }, (result: any) => {
      this.notificationService.notify({ severity: "error", summary: `Error`, detail: `Unable to update Projeto` });
    });
  }

  form0LoadData(event: any) {
    if (event.property == 'Cliente') {
          this.cproj3Ds.getPessoas(`${event.filter}`, event.top, event.skip, `${event.orderby}`, true, null, null, null)
      .subscribe((result: any) => {
          this.getPessoasResult = result.value;

      this.getPessoasCount = result['@odata.count'];
      }, (result: any) => {
    
      });
    }
  }
}
