/*
  This file is automatically generated. Any changes will be overwritten.
  Modify tarefas-por-projeto.component.ts instead.
*/
import { ChangeDetectorRef, ViewChild, AfterViewInit, Injector, OnInit, OnDestroy } from '@angular/core';
import { Router, ActivatedRoute } from '@angular/router';
import { Location } from '@angular/common';
import { Subscription } from 'rxjs';

import { DialogService, DIALOG_PARAMETERS, DialogRef } from '@radzen/angular/dist/dialog';
import { NotificationService } from '@radzen/angular/dist/notification';
import { ContentComponent } from '@radzen/angular/dist/content';
import { HeadingComponent } from '@radzen/angular/dist/heading';
import { DropDownComponent } from '@radzen/angular/dist/dropdown';
import { GridComponent } from '@radzen/angular/dist/grid';

import { CprojdsService } from '../cprojds.service';

export class TarefasPorProjetoGenerated implements AfterViewInit, OnInit, OnDestroy {
  // Components
  @ViewChild('content1') content1: ContentComponent;
  @ViewChild('pageTitle') pageTitle: HeadingComponent;
  @ViewChild('projetosFilter') projetosFilter: DropDownComponent;
  @ViewChild('grid0') grid0: GridComponent;

  router: Router;

  cd: ChangeDetectorRef;

  route: ActivatedRoute;

  notificationService: NotificationService;

  dialogService: DialogService;

  dialogRef: DialogRef;

  _location: Location;

  _subscription: Subscription;

  cprojds: CprojdsService;

  getProjetosResult: any;

  parameters: any;

  tarefas: any;

  constructor(private injector: Injector) {
  }

  ngOnInit() {
    this.notificationService = this.injector.get(NotificationService);

    this.dialogService = this.injector.get(DialogService);

    this.dialogRef = this.injector.get(DialogRef, null);

    this.router = this.injector.get(Router);

    this.cd = this.injector.get(ChangeDetectorRef);

    this._location = this.injector.get(Location);

    this.route = this.injector.get(ActivatedRoute);

    this.cprojds = this.injector.get(CprojdsService);
  }

  ngAfterViewInit() {
    this._subscription = this.route.params.subscribe(parameters => {
      if (this.dialogRef) {
        this.parameters = this.injector.get(DIALOG_PARAMETERS);
      } else {
        this.parameters = parameters;
      }
      this.load();
      this.cd.detectChanges();
    });
  }

  ngOnDestroy() {
    this._subscription.unsubscribe();
  }


  load() {
    this.cprojds.getProjetos(null, null, null, null, null, null, null, null)
    .subscribe((result: any) => {
      this.getProjetosResult = result.value;
    }, (result: any) => {

    });
  }

  projetosFilterChange(event: any) {
    this.cprojds.getTarefas(`Projeto eq ${event.Projeto1}`, null, null, null, null, `Pessoa,Projeto1`, null, null)
    .subscribe((result: any) => {
      this.tarefas = result.value;
    }, (result: any) => {

    });
  }
}
